// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Phase05.Search;

namespace Phase05.Migrations
{
    [DbContext(typeof(InvertedIndex))]
    partial class InvertedIndexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Phase05.DataSet.Document", b =>
                {
                    b.Property<int>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Phase05.DataSet.Word", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Value");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Phase05.DataSet.WordDoc", b =>
                {
                    b.Property<string>("WordId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DocId")
                        .HasColumnType("int");

                    b.HasKey("WordId", "DocId");

                    b.HasIndex("DocId");

                    b.ToTable("WordDocs");
                });

            modelBuilder.Entity("Phase05.DataSet.WordDoc", b =>
                {
                    b.HasOne("Phase05.DataSet.Document", "Doc")
                        .WithMany("WordDocs")
                        .HasForeignKey("DocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Phase05.DataSet.Word", "Word")
                        .WithMany("WordDocs")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doc");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("Phase05.DataSet.Document", b =>
                {
                    b.Navigation("WordDocs");
                });

            modelBuilder.Entity("Phase05.DataSet.Word", b =>
                {
                    b.Navigation("WordDocs");
                });
#pragma warning restore 612, 618
        }
    }
}
